src/style/ieee/mod.rs
I think it would be great to have an option to not abbreviate journal names in the IEEE style. For our project, we would really need it. This PR adds that option, making sure that the default stays the same (i.e, to abbreviate journal names by default)
=> Add option to turn off abbreviation of journals

src/style/mod.rs
Fixes #48 (and by extension, https://github.com/typst/typst/issues/1330).
Now this:
```rb
#set cite(style: "alphanumerical")
@Zeltner2021[p.~7]
```
generates
```diff
-[Zel+21]
+[Zel+21, p. 7]
```
and this:
```rb
#set cite(style: "chicago-author-title")
@Zeltner2021[p.~7].
```
generates
```diff
-Zeltner et al., “Monte Carlo Estimators for Differential Light Transport”
+Zeltner et al., “Monte Carlo Estimators for Differential Light Transport,” p. 7
```
=> Supplements in Alphanumeric and AuthorTitle style

src/lib.rs
I've run the following commands for testing. Is that the correct test workflow?
```bash
cargo build --features cli
./target/debug/hayagriva apatest.bib reference --style apa
```
Now the output is as expected.
> Alloy, L.B., Kelly, K., Mineka, et al. (1990). inbook: Comorbidity of anxiety and depressive disorders: A helplessness-hopelessness perspective. In J. Maser & C. Cloninger (Eds.), Comorbidity of mood and anxiety disorders (pp. 499–543). American Psychiatric Press.
> Alloy, L.B., Kelly, K., Mineka, et al. (1990). incollection: Comorbidity of anxiety and depressive disorders: A helplessness-hopelessness perspective. In J. Maser & C. Cloninger (Eds.), Comorbidity of mood and anxiety disorders (pp. 499–543). American Psychiatric Press.
=> Fix missing container for type anthos (#72)

src/csl/taxonomy.rs
This implements a fix suggested entirely by @zepinglee 
The issue, which is described in more detail below, is that hayagriva fails to find the volume when it is stored in the articles parent. 
https://github.com/typst/typst/issues/2643
=> fix volume reference

Cargo.toml
This is the end!
This will ensure that typst/typst doesn't have `syn1` in its dependency tree anywhere, and should thus yield compile time improvement.
=> Update `strum` to eliminate `syn1`-dependency

src/csl/taxonomy.rs, src/interop.rs, src/lib.rs
This PR adds three fields, abstract, annote, and genre; all as `FormatableString`.
The first two are also extracted from the BibLaTeX input if present. The genre field, seemingly, has no equivalent in bib files.
This will close #101.
Let me know if I should change something or add more fields. Most other fields that are still missing seem more complex and require discussion how hayagriva should manage them.
=> Add abstract, annote, and genre fieldss

src/csl/taxonomy.rs
The modify version of hayagriva tries to find the `editor` of the entry's container if it doesn't have `editor` itself. This is inspired by <https://github.com/typst/hayagriva/pull/82#discussion_r1397018367>.
=> Fix editor reference (#94)

docs/file-format.md
And its use to provide the article number for journal articles.
Closes #84.
=> Add documentation for `serial-number.serial`

docs/file-format.md
Changed the outdated link in the file format documentation. Fixes #120
=> docs: updated links to example file in file-format.md #120

src/csl/mod.rs
Fix #85.
The issue is that in some instances (such as in #85), the quotes are not in a `Text` but another `Elem`.
My solution to this also considers `Text` if it is the only child of a surrounding `Elem`.
Since I don't know the architecture well, my hack might be supoptimal. Perhaps a `flatten` function on `ElementChild` makes more sense?
Also: How do you want me to add a test for this?
=> Fix Pulling Punctuattion into Quotation marks

src/types/numeric.rs
Fix #103.
Changes the `NumericValue::range` method to return a range for a single number.
=> Fix Issue #103

src/csl/mod.rs
This PR fixes tests failing when they are not executed in the correct working directory.
=> Use workspace folder instead of CWD for file paths in test

docs/file-format.md, src/lib.rs
- ~Fail on unknown fields;~
- Fix doc comments; 
- Fix documentation for DOI (fix #110)
=> Fix docs for DOI

src/csl/taxonomy.rs
The citeproc tests did not handle `page-first` correctly, because it is not stored as a JSON field but is calculated from `page`.
Makes 5 more citeproc tests pass.
=> Fix page_first for citeproc test

src/csl/mod.rs
Changed `BibliographyDriver::finish` to not _take_ the locator from the speculative items. That lead to the locator of `last` to always be `None`, which caused #122.
Does anyone know why the `take` was there?
Fixes #122.
=> Fix Issue #122

src/types/persons.rs
This PR fixes the handling of initials when no delimiter is provided. Previously, citation styles that initialized without a delimiter (e.g., Vancouver) were formatted incorrectly. 
For example:
> **Doe J J.** World's Best Paper. Journal. 2025;99(9): 1–99.
instead of 
> **Doe JJ.** World's Best Paper. Journal. 2025;99(9): 1–99.
To fix this, we no longer add a space if no delimiter is passed.
Fixes #137.
=> fix: handle initials correctly

src/csl/rendering/mod.rs, tests/citeproc.rs
From https://github.com/typst/citationberg/issues/4#issuecomment-2009709750
> I found the problem is due to `substitute` and `choose` working together. (Its actually a problem of `typst/hayagriva`)
> 
>    1. `substitute` will cause any subsequent `query` to variables, in this case, the `title`, suppressed if that variable is queried once before.
> 
>    2. `choose` actually calls `query` to `title`  two times, the first time to find out which branch makes sense and the second to render.
> 
>    3. therefore the second time is suppressed and resulting in no title.
> 
> 
> A simple fix can be to do a silent lookup on the first `query` of `choose`, much like what is done in `Test::will_have_info(..)`.
> 
> This is the output from OP's bib after applying the fix:
> 
> ```
> Definition and …
```
=> Fix citation suppresses title when no author provided

src/csl/sort.rs, tests/citeproc-pass.txt
Fixes sorting of citation items being case sensitive when using a standard variable (e.g. `title`) as the sort key.
Citeproc test `sort_CaseInsensitiveCitation`[^1] now passes.
[^1]: https://github.com/citation-style-language/test-suite/blob/4001cdada66cd30f2ba1b8ae45a8da20f407dec0/processor-tests/humans/sort_CaseInsensitiveCitation.txt
=> Ensure sorting items by standard variable is case-insensitive

.github/workflows/ci.yml, src/csl/archive.rs, src/csl/mod.rs, src/lib.rs, src/types/mod.rs, tests/archiver.rs
=> Add clippy and formatting to CI

docs/file-format.md
Change the example date on `docs/file-format.md` from `2020-11-12` to `2020-11-30` to avoid confusion between day and month. Different countries have different date formats, so having both numbers beneath 12 might be confusing.
=> docs: change example url access date

docs/file-format.md
Documents the changes made in PR https://github.com/typst/hayagriva/pull/102.
@Drodt, could you contribute an example for `annote`? I am not familiar with this annotation and was hoping you could provide an example.
=> Add `abstract`, `annote`, and `genre` to documentation

src/csl/taxonomy.rs, src/interop.rs, src/types/strings.rs
This PR is to address issue #173, which was that hayagriva did not use the BibTex `shorttitle` field for short titles in CSL. In order to fix this issue, I made two changes:
1. In [interop.rs](https://github.com/typst/hayagriva/compare/main...pjtsearch:fix-short-titles?expand=1#diff-f2d7ad31a3f6f942aa18f5b56f944448cdf5f10c83d0ea16e39caf36157247c7), I added functionality for detecting if the BibTex `shorttitle` exists and adding it to the `FormatString` if it does.
2. In [taxonomy.rs](https://github.com/typst/hayagriva/compare/main...pjtsearch:fix-short-titles?expand=1#diff-702ef24022db1313b47f2d64bc684ce2aee610ab03badbf79cf6cb50eb692559), I fixed the code for `StandardVariable::Title` and `StandardVariable::TitleShort` being switched around. Previously, hayagriva would always select the …
=> Fix not using short titles

src/main.rs
It used to be (almost) identical to `hayagriva reference`, only returning citations formatted for a reference and not for in-text usage.
=> Fix 'hayagriva cite' command

docs/file-format.md, src/csl/taxonomy.rs, src/interop.rs, src/lib.rs, tests/data/basic.yml
Reviewing #218, I was looking into how `note` and `annote`/`annotation` are defined and used by CSL and BibLaTeX and learned that there are big discrepancies.
TL;DR: `note` and `annote` mean the reverse in CSL and BibLaTeX, CSL styles mostly use both as if there were no difference
Let's start by seeing what the [CSL spec ](https://docs.citationstyles.org/en/stable/specification.html?#appendix-iv-variables) says about both: 
> **annote**
> 
> Short markup, decoration, or annotation to the item (e.g., to indicate items included in a review);
> For descriptive text (e.g., in an annotated bibliography), use note instead
> 
> **note**
> 
> Descriptive text or notes about an item (e.g. in an annotated bibliography)
Compare this with the [BibLaTeX …
=> Remove the `annote` field from the data model

src/csl/rendering/mod.rs, src/csl/taxonomy.rs, src/interop.rs, src/lib.rs, src/types/mod.rs
#155 introduced a problem where BibLaTeX files with invalid page ranges such as `150--es` would crash the compiler. This PR makes them `MaybeType`d again. I ran [the file that originally showed us the crash](https://github.com/Dherse/masterproef/blob/9851952f04632a739540b36e85b26e60ba2bc298/masterproef/assets/references.bib) through the BibLaTeX parsing with success.
=> Make `page-range` `MabeType`d again

docs/file-format.md
The `title` example was seemingly invalid YAML. Adding quotes fixes this
=> Fix yaml syntax problem in file-format.md

src/main.rs
Previously, the CLI used clap's PossibleValueParser, which only supports parsing strings. However, hayagriva was expecting to parse Format directly. This caused a panic in clap, when trying to convert the String to Format.
With this patch, Format implements ValueEnum, so we can use clap::value_parser to create an EnumValueParser to parse the Format.
=> Fix --format CLI flag

src/lang/mod.rs
Similar to `"`, `”`, `«`, and other such characters, an apostrophe can mark a quotation, in which case the character after it may need to be upper case. Before this commit, Hayagriva always considered the character after an apostrophe to be within a word, and therefore lowercased it.
Closes #196
=> Apostrophe should not always cause step to return CharClass::InWord

src/types/page.rs
This fixes #241, which is a bug caused by incorrectly splitting the page ranges into groups.
The index calculation fails to account for a multibyte character at the end of a pages group. The subsequent split operation on the incorrect index leads to a crash, as described in the issue.
Examples:
```bib
@article{foo,
...
pages     = {321--},
...
}
@article{bar,
...
pages     = {321–},
...
}
```
Both page ranges are converted to a `321` followed by `–`, which is an utf8 character with multiple bytes
In addition to the fix, I've added a few tests for this and removed the string window in favor of the chars iterator from the std.
=> Fix crash on multibyte char in page ranges #241

README.md
- There should be only one H1 heading in a Markdown file. Fix H1 "Usage" to H2.
- See: https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md025---multiple-top-level-headers-in-the-same-document 
- There should be one blank line before the code block. Add blank lines.
- See: https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md031---fenced-code-blocks-should-be-surrounded-by-blank-lines
=> Fix Markdown warnings in README: multiple top-level headers and code blocks without surrounded blank lines

src/types/persons.rs, tests/citeproc-pass.txt
Fixes #137
Some styles, such as `vancouver`, require there to be nothing between initials, so `Astley, Rick Gavin` would be formatted as `Astley, RG` instead of `Astley, R. G.` (more usual) or `Astley, R G` for example. However, even when setting `initializer-with=""` (empty delimiter), Hayagriva was still forcing whitespaces between initials.
It was thought that #150 would have fixed it by only adding whitespaces if a delimiter was indeed specified, but it actually didn't change anything as **there is always a delimiter** - however, it is sometimes **an empty string**. While adding an explicit check for empty strings would have fixed this specific problem, it turns out Hayagriva's behavior of forcing a whitespace to always be added after the delimiter, replacing any of its trailing …
=> Fix handling of trailing whitespaces in initials' delimiters

.gitattributes, tests/citeproc.rs, tests/common/mod.rs
This PR fixes the following CRLF/LF problems for Windows dev. (only affects test documents)
On Windows, `git clone` may automatically convert LF to CRLF. (See [`git config core.autocrlf`](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration.html#_core_autocrlf).)
For tests expecting multiple lines, the RESULT section will get corrupted, leading to tons of failures.
For example,
https://github.com/citation-style-language/test-suite/blob/d2bd47ff09db6e2995aeed2be0b096b12c0f8f70/processor-tests/humans/variables_TitleShortOnShortTitleNoTitleGroup.txt#L5-L9
```
>>==== RESULT ====>>
Check this out: My Short Title is from title-short
Check this out:
Check this out:
<<==== RESULT ====<<
```
<details>
<summary>truncated output of <code>git clone … && cargo test --features …
=> Fix CRLF/LF problems for Windows dev

src/interop.rs
As in §3.14.7 of the [biblatex documentation](https://ftp.mpi-inf.mpg.de/pub/tex/mirror/ftp.dante.de/pub/tex/macros/latex/contrib/biblatex/doc/biblatex.pdf).
Addresses #260.
=> Add translation for pubmed eprint

src/interop.rs
This fixes issue #266.
Other than what the title of the issue suggests, `PersonRole::Unknown` can still not be serialized, deciding [on this](https://github.com/typst/hayagriva/issues/266#issuecomment-2633418457) is left to a later PR.
Instead, the PR adds some conversions for editor types the biblatex manual does not specify. Support for the `scriptwriter` type is justified by [zotero-better-biblatex's output](https://github.com/retorquere/zotero-better-bibtex/blob/c617185750df065f597a54b447a5b71f690777e4/test/fixtures/export/Exporting%20item%20type%20film%20merges%20scriptwriter%20with%20other%20contributors%20%232802.biblatex#L8). Support for the `producer` type is based on use in both [`biblatex-chicago`](https://markov.htwsaar.de/tex-archive/macros/latex/contrib/biblatex-contrib/bibla …
=> Add conversions for movie-related roles

.github/workflows/archive.yml, .github/workflows/ci.yml, tests/archiver.rs
Should avoid PRs wrongfully failing CI.
Also bumps Rust toolchain version on CI to Rust 1.83.0 since our deps have bumped their versions.
=> Run archiver tests weekly instead of on CI

src/csl/rendering/names.rs, tests/citeproc-pass.txt, tests/citeproc.rs, tests/local/name_PartInheritsFormatting.txt
When using font-variant="small-caps" on the <name> element in CSL styles, this formatting wasn't properly inherited by the individual name parts, causing the styling to be ignored. This fix ensures that font-variant styling is correctly propagated from the parent <name> element to child name parts (given name and family name) while maintaining the behavior where connector words like "and" remain in normal text.
This allows for proper small-caps styling of author names in bibliography styles like IEEE while keeping connector words in regular formatting.
Fixes #175.
=> Propagate font-variant from name element to name parts

src/interop.rs
This is meant to close #295 :
The `type` field (not entry type) in biblatex is used to set `genre`, regardless of entry type.  I think this is appropriate for all uses of `type`; biblatex's documentation states `type` is "The type of a manual, patent, report, or thesis. This field may also be useful for the custom types listed in § 2.1.3.", while Hayagriva's file format states `genre` is "Type, class, or subtype of the item (e.g. "Doctoral dissertation" for a PhD thesis; "NIH Publication" for an NIH technical report). Do not use for topical descriptions or categories (e.g. "adventure" for an adventure movie).".
The `number` field is more of a problem.  Biblatex's documentation describes it as "The number of a journal or the volume/number of a book in a series."  However, it then goes on …
=> biblatex `type` to `genre`, `number` to `serial` for non-article.

src/csl/rendering/mod.rs, tests/local/date_DateBCAdjusted.txt
Fixes #333.
A regression from #235, fixed by this PR, caused negative years to always be displayed as AD instead of BC.
Thanks to @Enivex for suggesting the fix.
=> Fix negative year rendering

src/csl/mod.rs, src/csl/rendering/mod.rs, src/types/time.rs, tests/local/date_DateBCAdjusted.txt
Previously it was hard coded to English (without leading spaces).
=> Use locale terms for AD/BC

.github/workflows/ci.yml
Bumps Rust CI to use 1.89.0 (same as typst/typst)
=> Bump Rust CI

src/lib.rs
Undo accidental regression from #383 that removed TransparentLocator from public exports (after #299).
Reported by @SillyFreak at https://github.com/typst/hayagriva/pull/383#issuecomment-3335993578 (thank you very much!).
=> Expose `TransparentLocator` again

src/csl/mod.rs
According to the CSL spec[^1] (emphasis mine):
> The presence of locators determines which position is assigned:
> 
>  - Preceding cite does not have a locator: if the current cite has a locator, the position of the current cite is “ibid-with-locator”. Otherwise the position is “ibid”.
>  - Preceding cite does have a locator: if the current cite has the same locator, the position of the current cite is “ibid”. If the locator differs the position is “ibid-with-locator”. **If the current cite lacks a locator its only position is “subsequent”.**
Prior logic only checked if the locators differed in any way, assigning "ibid with locator" if so. But that included differing by the previous citation having a locator and the current one not having one, whereas that case should be handled …
=> Fix wrong ibid position, test transparent locators
